### ISSUE TITLE
Project needs a different name

### ISSUE THREAD

**Issue by maisieccino** [mbellgb/easyticket#1]
It appears that Easyticket might not be the best name, it's not the most unique name in the world (although it's not trademarked in the UK). Also worth pointing out that @easyticket has already been taken (although stagnant).

Any suggestions for names? The options so far seem to be:

* Remain as Easyticket, just name the github org something like easy-ticket instead.
* Shorten it (ETicket?), although "E" risks being misunderstood as "Electronic".
* Other name ideas:
  * Openticket
  * Openstub
  * Steward/Usher
  * OTV (Open Ticket Vendor)
  * OTIS (Open-sourced Ticketing Information & Sales)
  * ETC (Easy Ticketing Control)

As you can see, I'm useless with names.

**Comment by savage-engineer** [comment]
I like Openticket. Additionally I think that the line of thinking you're taking with the Steward/Usher idea is good, allows for a bit more creativity with branding/identity imo. Marshal might be another name to consider amongst those two.

Don't have a particular inclination towards the abbreviations, as abbreviations are easy to step on other peoples toes with. I additionally think that abbreviations can be pretty dry and the meaning behind them often not memorable.

**Comment by maisieccino** [comment]
@savage-engineer totally agree, I'm personally leaning towards Openticket or Steward at this point. I mean, one option could be to reserve the warmer/creative naming for an app further down the line. Idk. But ultimately the name for the server doesn't need to be _overly_ brilliant imo.

I mean, who thought that "Windows", "Linux" or "Macintosh" sounded cool? :joy:

**Comment by maisieccino** [comment]
I think openticket is going to be the name for now. :tada:
